### ISSUE TITLE
Rework command line interface

### ISSUE THREAD

**Issue by lorc** [xen-troops/zephyr-xenlib#69]
Current `xu` command line interface is clunky. For example, for some reason we use flags for mandatory options, which is  defiles established practices. Moreover flags are locked in positions. For example #57 introduces new `-c` flag for  `xu create` command, but you can't use change order of flags. Only this command is possible:

```
# xu create -d <domid> -c <config_name>
```

You can't even swap the arguments:

```
# xu create -c <config_name> -d <domid>  # this will not work
```

I propose to align  use of flags with established standard: only optional parameters needs flag, all mandatory options are positional and require no additional flags. For example:

```
# xu console 1
# xu create domd -d 1
# xu create domd
# xu destroy 1
```

This is a great time for this, before we release the fist "stable" version.

**Comment by GrygiriiS** [comment]
Before reworking cmd interface it shell be documented. Or documentation shell be created for the new one.
