### ISSUE TITLE
Domain name parsing in shell commands

### ISSUE THREAD

**Issue by lorc** [xen-troops/zephyr-xenlib#71]
Shell commands should accept both domain ID and domain name. E.g.

```
xu console DomD
```

and 

```
xu console 1
``` 

Should do the same (providing that DomD have id 1)

**Comment by GrygiriiS** [comment]
In my opinion It's overhead from Zephyr point of view. What should be there is smth like "xu list" which should list name/xen_id/<some info>. Then ids used in all other commands.

<some info> : <state ::= "created" | "running" | "paused";> 

From Zephyr point of view there should be always static (configurable) number of supported domains and it's probably time to strictly define domainID/domainNum from Zephyr point of view for cmdline. Of course, It potentially might be possible to have static and dynamic domains (static - configured statically, dynamic - dominfo obtained from some source), but over all number of domains will always be static.

**Comment by lorc** [comment]
We already have AOS use case where they download domains over internet and run them. In this case number of domains is practically unbound. It is limited only by number of free resources.

**Comment by GrygiriiS** [comment]
I think no need to play with dom names and better (a) use numbering not connected to Xen domain id (b) add "list" command to obtain Xen domain id.

**Comment by lorc** [comment]
What is the purpose of the separate domain number then? 

I want interface to resemble used in "xl" tool as it is already familiar for almost everyone working with Xen.

**Comment by GrygiriiS** [comment]
> What is the purpose of the separate domain number then?
> 
> I want interface to resemble used in "xl" tool as it is already familiar for almost everyone working with Xen.

I meant (a) or (b).

 If you want the same functionality as in XEN Linux dom0 - use linux. If you port all of it in Zephyr - you'll get the same problems and disadvantages as in the Linux dom0, so what will be the sense of doing it. 
And xen console here definitely not a product feature.

**Comment by lorc** [comment]
It is not a product feature, but we, as developers, spending too much time in the console. So it is in our interest to have convenient console interface. 

Anyways, I agree with you. We need `xu list` command. I am surprised that it is not implemented yet, actually.

**Comment by GrygiriiS** [comment]
not only 'xu list', but also some way to retrieve and maintain current xen state. Here I'm referring to domains created not by dom0 (dom0less boot), which we might/might not wanna control, but we definitely want console access in case "hvc0" is used.

Some summary:
- dom ctrl commands should accept xen_dom_id
- xen_dom_id is known or can be obtained through `xu list`

potential addon:
- `xu update` command to retrieve Xen state, so foreign xen_dom_id can be used at least for HVC console access

**Comment by lorc** [comment]
Well, I am no sure if dom0 can access dom0less HVC consoles. AFAIK, those consoles are managed by Xen directly. Is there an API to switch dom0less HVC to Dom0 console server?
